CREATE DATABASE springapp;

GRANT ALL ON springapp.* TO springappuser@'%' IDENTIFIED BY 'root';
GRANT ALL ON springapp.* TO springappuser@localhost IDENTIFIED BY 'root';

USE springapp;

CREATE TABLE products (
  id INTEGER PRIMARY KEY,
  description varchar(255),
  price decimal(15,2)
);
CREATE INDEX products_description ON products(description);

CREATE TABLE users (
USER_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(45) NOT NULL,
PASSWORD VARCHAR(45) NOT NULL,
FULLNAME VARCHAR(100) NOT NULL,
ENABLED tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_roles (
USER_ROLE_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
USER_ID INT(10) UNSIGNED NOT NULL,
AUTHORITY VARCHAR(45) NOT NULL,
KEY FK_user (USER_ID),
CONSTRAINT FK_user_roles FOREIGN KEY (USER_ID) REFERENCES users (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

